_BASE_: Base-COCO-InstanceSegmentation.yaml
MODEL:
  WEIGHTS: "output/m2f_binary_lvis_ow/model_final.pth"
  META_ARCHITECTURE: "SegPrompt"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead_Open"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "SegPrompt_MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    QUERY_REPEAT : 10
    QUERY_REPEAT_ONLY_MATCH : True
    NUM_OPEN_QUERIES : 300
    FREEZE_BACKBONE: True
    EXAMPLE_SUP: True
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      
SOLVER:
  BASE_LR: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
SEED : 1
INPUT:
  IMAGE_SIZE: 1024
DATASETS:
  TRAIN: ('lvis_v1_train_ow',)
  TEST: ('lvis_v1_val',)
OUTPUT_DIR: "output/segprompt_lvis_ow"
TEST:
  EVAL_PERIOD: 900000
